name = "IsingCats"
uuid = "6ea33c6f-e974-4819-93fb-37c50cea74fa"
authors = ["James Fairbanks <jpfairbanks@gmail.com>", "Anna Knorr", "Amy Searle", "Grant Generaux"]
version = "0.1.0"

[deps]
Catlab = "134e5e36-593f-5add-ad60-77f754baafbe"